# Основные настройки
main_settings:
  # Форматирование текста.
  # LEGACY - цвет через & и hex &#
  # LEGACY_ADVANCED - улучшенный аналог legacy с поддержкой &## формата hex
  # MINIMESSAGE - цвет через <цвет>
  # MINIMESSAGE был добавлен в новых версиях (1.17+)
  serializer: LEGACY
  # Команда рандомной телепортации (указывается без /)
  rtp_command: 'rtp'
  # Алиасы к команде рандомной телепортации
  rtp_aliases: ['randomteleport', 'ovrandomteleport']
  # Должен ли быть включён таб-комплит у команды ртп?
  rtp_tab_complete: true
  # Название дефолтного канала.
  # Указанный канал будет использован в качестве основного при вводе команды /rtp
  # Если канал не указан - то игроку будет необходимо ввести имя канала вручную
  default_channel: 'default'
  # Включить ли поддержку PlaceholderApi?
  papi_support: true
  # Отправлять ли анонимную статистику (советую не отключать)
  enable_metrics: true
  # Проверять ли на наличие обновлений (советую не отключать)
  update_checker: true

# Каналы рандомной телепортации
# Вы можете создавать свои каналы, основываясь на уже заранее заготовленных в плагине
channels:
  # Базовый канал (право на использование - rtp.channel.имя_канала т.е. в данном случае rtp.channel.default)
  default:
    # Имя файла, где будет располагаться настройка канала. (Данный файл должен присутствовать в папке channels)
    # Если имя не указано - настройка осуществляется в самом конфиге (по аналогии с deluxemenus)
    file: 'default.yml'
  # Канал который будет телепортировать игрока рядом с другими игроками
  # Дистанция телепортации варьируется, от 30 до 60 блоков от игрока
  near:
    # Вы можете вынести все настройки в этот конфиг, если вам так будет проще.
    file: 'near.yml'
  # Канал который будет телепортировать игрока рядом с регионами
  # Дистанция телепортации варьируется, от 30 до 60 блоков от игрока
  base:
    file: 'base.yml'

# Сообщения плагина (сообщения от prefix до already_teleporting могут применяться к каналам)
# Формат хекса - &#IIIDDD
# Если вы хотите отключить сообщение - укажите ''
messages:
  prefix: '&7&l(&5&lOvRandomTeleport&7&l) &6»&r'
  # Сообщения ниже могут быть применены так же и к каналам
  no_perms: '%prefix% &cУ вас не достаточно прав на использование данного канала.'
  invalid_world: '%prefix% &fВы не можете использовать данный канал рандомной телепортации в этом мире.'
  not_enough_players: '%prefix% &cНа сервере не достаточно игроков чтобы телепортироваться по данному каналу. Нужно: &6%required% игроков.'
  not_enough_money: '%prefix% &cУ вас не достаточно денег чтобы телепортироваться по данному каналу. Стоимость: &6%required% монет.'
  not_enough_hunger: '%prefix% &cУ вас не достаточно очков голода чтобы телепортироваться по данному каналу. Необходимо: &6%required%.'
  not_enough_experience: '%prefix% &cУ вас не достаточно очков опыта чтобы телепортироваться по данному каналу. Необходимо: &6%required%.'
  cooldown: '%prefix% &fВы еще не можете телепортироваться по данному каналу. Подождите еще &6%time%'
  moved_on_teleport: '%prefix% &cВы двинулись! Телепортация отменена.'
  teleported_on_teleport: '%prefix% &cВы телепортировались в процессе РТП! Телепортация отменена.'
  damaged_on_teleport: '%prefix% &cВы получили урон! Телепортация отменена.'
  damaged_other_on_teleport: '%prefix% &cВы нанесли урон! Телепортация отменена.'
  fail_to_find_location: '%prefix% &6Не удалось подобрать необходимую локацию. Попробуйте снова позже!'
  # Далее идут сообщения команды rtp и т.д.
  incorrect_channel: '%prefix% &cУказанного канала рандомной телепортации не существует!'
  channel_not_specified: '%prefix% &cВам необходимо указать канал рандомной телепортации!'
  canceled: '%prefix% &aТелепортация отменена!'
  # Заполнители плейсхолдеров PlaceholderAPI
  placeholders:
    no_cooldown: '&aКулдаун отсутствует!'
    no_value: '&cОтсутствует'
    # Плейсхолдеры времени
    time:
      hours: ' ч. '
      minutes: ' мин. '
      seconds: ' сек. '
  # Раздел для админских команд
  admin:
    reload: '%prefix% &aПлагин успешно перезагружен!'
    unknown_argument: '%prefix% &cВы введи недопустимы(й/е) аргумент(ы) к команде!'
    player_not_found: '%prefix% &cУказанный игрок не найден!'
    admin_help: |-
      %prefix% Помощь по админ.командам.
      &a/rtp admin reload &f- перезагрузить плагин
      &a/rtp admin forceteleport <игрок> <канал> &f- телепортировать игрока по указанному каналу
  